image: python:3.7.2

services:
  - mysql:8.0.11

variables:
  MYSQL_ROOT_PASSWORD: Loknag#123
  MYSQL_USER: root
  Host: mysql
  User: magnram_jacal
  Password: jacal
  Database: magnram_pu

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - mysql -V
  - pip install -r requirements.txt

test:
  script:
  - python manage.py test --keepdb --settings conf.test_settings
