test:
  script: python3 djangoproject/manage.py test app
#  - apt-get update
#  - wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
#  - tar xvf Python-3.6.3.tgz
#  - cd Python-3.6.3
#  - ./configure --enable-optimizations
#  - make -j8 build_all
#  - make -j8 install
#  - cd ..
#  - python3.6 -m pip install --upgrade pip
#  - python3.6 -m pip install -r requirements.txt
#  - python3.6 -m pip install --upgrade django-crispy-forms
#  - python3.6 -m pip install pillow
#  - python3.6 djangoproject/manage.py test app
