image: python:3.7.2

services:
  - mysql:8.0.11

variables:
  Host: mysql
  User: magnram_jacal
  MYSQL_ROOT_PASSWORD: jacal
  Database: magnram_pu

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt

test:
  script:
  - python manage.py test
