# Generated by Django 2.1.5 on 2019-02-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190210_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='company',
            new_name='startup',
        ),
    ]
