# Generated by Django 2.1.5 on 2019-02-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190207_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='company_id',
            new_name='company',
        ),
    ]
