# Generated by Django 2.1.5 on 2019-02-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190210_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='employees',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
