# Generated by Django 2.1.5 on 2019-02-10 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190211_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='phase',
        ),
        migrations.AddField(
            model_name='startup',
            name='phase',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Phase'),
            preserve_default=False,
        ),
    ]
