# Generated by Django 2.1.5 on 2019-02-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190211_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='images/'),
        ),
    ]
