# Generated by Django 2.1.5 on 2019-02-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_startup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Address'),
        ),
    ]
