# Generated by Django 2.1.5 on 2019-02-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190212_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Address'),
        ),
    ]
