# Generated by Django 2.1.5 on 2019-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190212_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='images/'),
        ),
    ]
