# Generated by Django 2.1.5 on 2019-02-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190212_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Address'),
        ),
    ]
