# Generated by Django 2.1.5 on 2019-02-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190218_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='event_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
