# Generated by Django 2.1.5 on 2019-02-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190218_1941'),
        ('app', '0020_person_address'),
    ]

    operations = [
    ]
