# Generated by Django 2.1.5 on 2019-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_merge_20190219_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
