# Generated by Django 2.1.5 on 2019-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190219_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Norway', max_length=120),
            preserve_default=False,
        ),
    ]
