# Generated by Django 2.1.5 on 2019-02-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='images/'),
        ),
    ]
