# Generated by Django 2.1.5 on 2019-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='images/no-background.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='images/'),
        ),
    ]
