# Generated by Django 2.1.5 on 2019-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190221_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='homepage',
            field=models.CharField(default='www.defaulthomepage.com', max_length=120),
            preserve_default=False,
        ),
    ]
