# Generated by Django 2.1.5 on 2019-02-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_startup_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
