# Generated by Django 2.1.5 on 2019-03-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190311_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
    ]
